sudo: required
services:
  - docker

before_install:
  - docker build -t kbhaskett/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kbhaskett/react-test npm test -- --coverage

after_success:
  - docker build -t kbhaskett/multi-client ./client
  - docker build -t kbhaskett/multi-nginx ./nginx
  - docker build -t kbhaskett/multi-server ./server
  - docker build -t kbhaskett/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kbhaskett/multi-client
  - docker push kbhaskett/multi-nginx
  - docker push kbhaskett/multi-server
  - docker push kbhaskett/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-multi
  env: DockerMulti-env
  bucket_name: elasticbeanstalk-us-east-2-338706605177
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY